//! Wire-format compatibility test for the preperoni iOS migration.
//!
//! See `docs/briefs/ios-yswift-handover.md` §4.4 in the consumer repo:
//! a binary update produced by the JS `yjs` library against the preperoni
//! schema must round-trip through these bindings without loss. The fixture
//! `tests/fixtures/preperoni_v1.bin` is regenerated by
//! `tests/fixtures/generate_preperoni_fixture.mjs` (a small Node script that
//! requires `yjs@13`).
//!
//! If this test fails after a `yrs` or `uniffi` bump, the bindings have
//! drifted from upstream Y.js wire format — block the release until you
//! understand why.

#![cfg(test)]

use crate::value::YrsValueKind;
use crate::YrsDoc;
use std::fs;
use std::path::PathBuf;

fn fixture_bytes() -> Vec<u8> {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("fixtures");
    p.push("preperoni_v1.bin");
    fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "fixture {:?} missing — regenerate via `node tests/fixtures/generate_preperoni_fixture.mjs`: {}",
            p, e
        )
    })
}

#[test]
fn js_emitted_preperoni_update_round_trips() {
    let doc = YrsDoc::new();
    let recipes = doc.get_map("recipes".to_string());
    let plans = doc.get_map("plans".to_string());

    let txn = doc.transact(None);
    txn.transaction_apply_update(fixture_bytes())
        .expect("apply_update");

    // recipes['rec_abc'] -> Y.Map
    assert_eq!(
        recipes.value_kind_at_key(&txn, "rec_abc".to_string()),
        Some(YrsValueKind::YMap)
    );
    let rec = recipes
        .get_map_at_key(&txn, "rec_abc".to_string())
        .expect("rec_abc map");
    // scalars on the recipe
    assert_eq!(
        rec.get_scalar_at_key(&txn, "title".to_string()),
        Some("\"Pasta\"".to_string())
    );
    assert_eq!(
        rec.get_scalar_at_key(&txn, "url".to_string()),
        Some("\"https://example.com/pasta\"".to_string())
    );
    assert_eq!(
        rec.get_scalar_at_key(&txn, "status".to_string()),
        Some("\"parsed\"".to_string())
    );
    // null scalar must round-trip as JSON null, not as a missing key
    assert_eq!(
        rec.value_kind_at_key(&txn, "image_url".to_string()),
        Some(YrsValueKind::Scalar)
    );
    assert_eq!(
        rec.get_scalar_at_key(&txn, "image_url".to_string()),
        Some("null".to_string())
    );
    // numeric — note Any::to_json normalises integers to "<n>.0"
    assert_eq!(
        rec.get_scalar_at_key(&txn, "servings".to_string()),
        Some("4.0".to_string())
    );

    // plans['2025-18'] -> Y.Map containing nested Y.Arrays
    assert_eq!(
        plans.value_kind_at_key(&txn, "2025-18".to_string()),
        Some(YrsValueKind::YMap)
    );
    let plan = plans
        .get_map_at_key(&txn, "2025-18".to_string())
        .expect("plan map");

    assert_eq!(
        plan.value_kind_at_key(&txn, "recipeIds".to_string()),
        Some(YrsValueKind::YArray)
    );
    let recipe_ids = plan
        .get_array_at_key(&txn, "recipeIds".to_string())
        .expect("recipeIds array");
    assert_eq!(recipe_ids.length(&txn), 1);
    assert_eq!(recipe_ids.to_a(&txn), vec!["\"rec_abc\""]);

    let locked = plan
        .get_array_at_key(&txn, "lockedUrls".to_string())
        .expect("lockedUrls array");
    assert_eq!(locked.length(&txn), 1);
    assert_eq!(
        locked.to_a(&txn),
        vec!["\"https://example.com/pasta\""],
    );

    // groceryJson is a string scalar containing serialised JSON
    assert_eq!(
        plan.get_scalar_at_key(&txn, "groceryJson".to_string()),
        Some("\"{\\\"items\\\":[]}\"".to_string())
    );
}

/// Reverse direction: build the same shape natively via the new inserter
/// constructors and prove we produce a binary update that decodes into a
/// structurally-identical doc when re-applied. This is the half of §4.4 the
/// brief calls "build in Rust, decode in JS" — we approximate the JS half by
/// re-applying our own update onto a second `YrsDoc` and checking the
/// projection (a full JS-decode requires a node runtime in CI; the JS->Rust
/// direction above already covers wire-format compatibility, so this test
/// mostly guards against accidental skew between our writer and reader).
#[test]
fn rust_produced_doc_round_trips_through_native_apply_update() {
    let producer = YrsDoc::new();
    let p_recipes = producer.get_map("recipes".to_string());
    let p_plans = producer.get_map("plans".to_string());

    let producer_update = {
        let txn = producer.transact(None);
        let rec = p_recipes.insert_map(&txn, "rec_abc".to_string());
        rec.insert(&txn, "title".to_string(), "\"Pasta\"".to_string());
        rec.insert(&txn, "status".to_string(), "\"parsed\"".to_string());
        rec.insert(&txn, "image_url".to_string(), "null".to_string());

        let plan = p_plans.insert_map(&txn, "2025-18".to_string());
        let ids = plan.insert_array(&txn, "recipeIds".to_string());
        ids.insert(&txn, 0, "\"rec_abc\"".to_string());
        plan.insert(&txn, "rerollCount".to_string(), "0".to_string());

        txn.transaction_encode_state_as_update()
    };

    let consumer = YrsDoc::new();
    let c_recipes = consumer.get_map("recipes".to_string());
    let c_plans = consumer.get_map("plans".to_string());
    {
        let txn = consumer.transact(None);
        txn.transaction_apply_update(producer_update)
            .expect("apply_update");
    }

    let txn = consumer.transact(None);
    let rec = c_recipes
        .get_map_at_key(&txn, "rec_abc".to_string())
        .expect("rec_abc");
    assert_eq!(
        rec.get_scalar_at_key(&txn, "title".to_string()),
        Some("\"Pasta\"".to_string())
    );
    let plan = c_plans
        .get_map_at_key(&txn, "2025-18".to_string())
        .expect("plan");
    let ids = plan
        .get_array_at_key(&txn, "recipeIds".to_string())
        .expect("ids");
    assert_eq!(ids.to_a(&txn), vec!["\"rec_abc\""]);
}
